__version__ = "0.1.0"
__name__ = "pycomptox"
__description__ = "A short description of my package"
__author__ = "Kunal"
__author_email__ = "your.email@example.com"
__url__ = "https://github.com/Kunal627/pycomptox"
__license__ = "OSI Approved :: MIT License"